# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solemne2', '0002_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(default=b'static/images/500x300.png', upload_to=b'static/images/'),
        ),
    ]
